In [19]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


from sklearn.model_selection import cross_val_score

from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

from sklearn.model_selection import GridSearchCV

from sklearn.tree import export_text

import random

In [20]:
df.drop_duplicates()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,Not_Canceled
36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,Canceled
36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,Not_Canceled
36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,Canceled
36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,Not_Canceled

In [21]:
df.booking_status.unique()

array(['Not_Canceled', 'Canceled'], dtype=object)

In [22]:
df['booking_status'] = df['booking_status'].map({'Canceled':0, 'Not_Canceled':1})

In [23]:
df.corr()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
no_of_adults,1.000000,-0.019787,0.103316,0.105622,0.011429,0.097287,0.076719,0.021841,0.026338,-0.192277,-0.047426,-0.119166,0.296886,0.189401,-0.086920
no_of_children,-0.019787,1.000000,0.029478,0.024398,0.034244,-0.047091,0.045983,-0.003076,0.025482,-0.036348,-0.016390,-0.021189,0.337728,0.124486,-0.033078
no_of_weekend_nights,0.103316,0.029478,1.000000,0.179577,-0.031111,0.046595,0.055357,-0.009894,0.027304,-0.067107,-0.020690,-0.026312,-0.004525,0.060593,-0.061563
no_of_week_nights,0.105622,0.024398,0.179577,1.000000,-0.048784,0.149650,0.032672,0.037376,-0.009305,-0.099764,-0.030080,-0.049344,0.022753,0.045994,-0.092996
required_car_parking_space,0.011429,0.034244,-0.031111,-0.048784,1.000000,-0.066445,0.015684,-0.015505,-0.000037,0.110909,0.027106,0.063810,0.061304,0.087922,0.086185
lead_time,0.097287,-0.047091,0.046595,0.149650,-0.066445,1.000000,0.143439,0.136814,0.006479,-0.135984,-0.045723,-0.078137,-0.062596,-0.101645,-0.438538
arrival_year,0.076719,0.045983,0.055357,0.032672,0.015684,0.143439,1.000000,-0.339689,0.018849,-0.018175,0.003919,0.026422,0.178605,0.053205,-0.179529
arrival_month,0.021841,-0.003076,-0.009894,0.037376,-0.015505,0.136814,-0.339689,1.000000,-0.042780,0.000341,-0.038615,-0.010718,0.054423,0.110552,0.011233
arrival_date,0.026338,0.025482,0.027304,-0.009305,-0.000037,0.006479,0.018849,-0.042780,1.000000,-0.015949,-0.012542,-0.001498,0.017898,0.018352,-0.010629
repeated_guest,-0.192277,-0.036348,-0.067107,-0.099764,0.110909,-0.135984,-0.018175,0.000341,-0.015949,1.000000,0.390810,0.539156,-0.174900,-0.011820,0.107287
no_of_previous_cancellations,-0.047426,-0.016390,-0.020690,-0.030080,0.027106,-0.045723,0.003919,-0.038615,-0.012542,0.390810,1.000000,0.468147,-0.063340,-0.003317,0.033728
no_of_previous_bookings_not_canceled,-0.119166,-0.021189,-0.026312,-0.049344,0.063810,-0.078137,0.026422,-0.010718,-0.001498,0.539156,0.468147,1.000000,-0.113684,0.027377,0.060179
avg_price_per_room,0.296886,0.337728,-0.004525,0.022753,0.061304,-0.062596,0.178605,0.054423,0.017898,-0.174900,-0.063340,-0.113684,1.000000,0.184381,-0.142569
no_of_special_requests,0.189401,0.124486,0.060593,0.045994,0.087922,-0.101645,0.053205,0.110552,0.018352,-0.011820,-0.003317,0.027377,0.184381,1.000000,0.253070
booking_status,-0.086920,-0.033078,-0.061563,-0.092996,0.086185,-0.438538,-0.179529,0.011233,-0.010629,0.107287,0.033728,0.060179,-0.142569,0.253070,1.000000

In [24]:
df=df[['lead_time', 'arrival_year','repeated_guest', 'avg_price_per_room', 'no_of_special_requests', 'booking_status']]

In [25]:
df.isnull().sum()

lead_time                 0
arrival_year              0
repeated_guest            0
avg_price_per_room        0
no_of_special_requests    0
booking_status            0
dtype: int64

In [26]:
df.booking_status.value_counts()

1    24390
0    11885
Name: booking_status, dtype: int64

In [27]:
# test train split

y = df['booking_status']

x = df.drop('booking_status',axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=0)

In [28]:
dtc = DecisionTreeClassifier(max_depth=3, random_state=0)
dtc.fit(x_train, y_train)
y_pred=dtc.predict(x_test)

print('accuracy_score', accuracy_score(y_test, y_pred))
print('f1_score', f1_score(y_test, y_pred))

accuracy_score 0.7817697326104934
f1_score 0.8430374727380875

In [29]:
# show tree (max depth=3)

r = export_text(dtc, feature_names=list(df.iloc[:,:5].columns))
print(r)

|--- lead_time <= 151.50
|   |--- no_of_special_requests <= 0.50
|   |   |--- avg_price_per_room <= 112.26
|   |   |   |--- class: 1
|   |   |--- avg_price_per_room >  112.26
|   |   |   |--- class: 0
|   |--- no_of_special_requests >  0.50
|   |   |--- lead_time <= 71.50
|   |   |   |--- class: 1
|   |   |--- lead_time >  71.50
|   |   |   |--- class: 1
|--- lead_time >  151.50
|   |--- avg_price_per_room <= 100.04
|   |   |--- no_of_special_requests <= 0.50
|   |   |   |--- class: 0
|   |   |--- no_of_special_requests >  0.50
|   |   |   |--- class: 1
|   |--- avg_price_per_room >  100.04
|   |   |--- no_of_special_requests <= 2.50
|   |   |   |--- class: 0
|   |   |--- no_of_special_requests >  2.50
|   |   |   |--- class: 1

In [30]:
test_data = x_test

test_data['target'] = y_test

test_data['y_pred']=y_pred

In [31]:
# only true negatives

test_data[(test_data['target'] == 0) & (test_data["y_pred"] == 0)]

,lead_time,arrival_year,repeated_guest,avg_price_per_room,no_of_special_requests,target,y_pred
15128,193,2017,0,65.00,0,0,0
16842,257,2017,0,101.50,0,0,0
11030,176,2018,0,125.10,0,0,0
2051,144,2018,0,131.70,0,0,0
3668,178,2018,0,88.50,0,0,0
...,...,...,...,...,...,...,...
9763,275,2018,0,62.80,0,0,0
29332,279,2018,0,110.00,0,0,0
2629,6,2017,0,127.00,0,0,0
2285,56,2018,0,130.05,0,0,0
12446,65,2018,0,136.80,0,0,0

In [32]:
# random record from only true negatives

(test_data[(test_data['target'] == 0) & (test_data["y_pred"] == 0)]).sample(1, random_state=1)

,lead_time,arrival_year,repeated_guest,avg_price_per_room,no_of_special_requests,target,y_pred
295,166,2018,0,110.0,0,0,0

In [33]:
# for see if have a diffrence in prediction, change a row record 

df.at[2663,['lead_time','arrival_year','avg_price_per_room' ]]=['151','2017','130']

In [34]:
# test train split

y = df['booking_status']

x = df.drop('booking_status',axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=0)

dtc = DecisionTreeClassifier(max_depth=5, random_state=0)
dtc.fit(x_train, y_train)
y_pred=dtc.predict(x_test)

print('accuracy_score', accuracy_score(y_test, y_pred))
print('f1_score', f1_score(y_test, y_pred))

test_data = x_test

test_data['target'] = y_test

test_data['y_pred']=y_pred

accuracy_score 0.8060277497013691
f1_score 0.8640257648953301

In [35]:
test_data[test_data.index==2663]

,lead_time,arrival_year,repeated_guest,avg_price_per_room,no_of_special_requests,target,y_pred
2663,151,2017,0,130,0,0,1